services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metisone_web
    env_file:
      - DATABASE/.env
      - .env.django
    working_dir: /app/src
    volumes:
      - /srv/metiz/static:/app/src/staticfiles:rw
      - /srv/metiz/media:/app/src/media:rw
    ports:
      - "8000:8000"
    networks:
      - metiz_network

networks:
  metiz_network:
    external: true
